# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tagName: '$(Build.BuildNumber)'
  imageName: '$(dockerId)/homepage:$(tagName)'
  latestImageName: '$(dockerId)/homepage:latest'

steps:
- script: docker build -f Dockerfile -t $(imageName) -t $(latestImageName) .
  displayName: 'docker build'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(imageName)
    docker push $(latestImageName)
  displayName: 'docker push'

- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: 'weihanli-vm'
    runOptions: inline

    inline: |
      kubectl set image deployment/homepage homepage=$(imageName) --record=true
