FROM node as builder

LABEL maintainer="WeihanLi"

# set working directory
WORKDIR /app

# install and cache app dependencies
COPY . /app

RUN yarn && yarn run build

FROM nginx

COPY --from=builder /app/dist/weihanli /usr/share/nginx/html

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
