apiVersion : apps/v1
kind: Deployment
metadata:
  name: "homepage"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "homepage"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "homepage"
    spec:
      containers:
        - name: "homepage"
          image: "weihanli/homepage"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 16Mi
