apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: homepage
  namespace: default
spec:
  tls:
  - hosts:
    - weihanli.top
    - www.weihanli.top
  rules:
  - host: weihanli.top
    http:
      paths:
      - backend:
          service:
            name: homepage
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: www.weihanli.top
    http:
      paths:
      - backend:
          service:
            name: homepage
            port:
              number: 80
        path: /
        pathType: Prefix
